# Generated by Django 3.1.7 on 2021-03-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='uri',
            field=models.FileField(blank=True, null=True, upload_to='items/'),
        ),
    ]
