# Generated by Django 3.1.5 on 2021-03-16 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210316_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
